name: cookfluencer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0  # 최신 버전 확인 후 수정
  firebase_messaging: ^15.1.3  # 최신 버전 확인 후 수정
  firebase_crashlytics: ^4.1.3  # 최신 버전 확인 후 수정
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  firebase_analytics: ^11.3.0
  cloud_firestore: ^5.3.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1  # 구글 폰트를 위한 google_fonts
  freezed_annotation: ^2.4.4  # 불변 모델 생성을 위한 Freezed
  json_annotation: ^4.9.0   # JSON 파싱을 위한 json_annotation
  flutter_riverpod: ^2.5.1  # 상태 관리를 위한 Riverpod
  riverpod_annotation: ^2.3.5  # 상태 관리를 위한 Riverpod
  hooks_riverpod: ^2.5.1     # Hook을 사용하기 위한 hooks_riverpod
  #  go_router: ^14.2.7  # 라우팅을 위한 go_router
  go_router: ^14.2.8  # 라우팅을 위한 go_router // 버전높일시 willScope 안먹힘
  carousel_slider: ^5.0.0   # 이미지 슬라이더를 위한 carousel_slider
  flutter_hooks: ^0.20.5    # Hook을 사용하기 위한 flutter_hooks
  shared_preferences: ^2.2.3  # 로컬 저장소를 위한 shared_preferences
  animations: ^2.0.11    # 애니메이션을 위한 animations
  cached_network_image: ^3.2.3  # 이미지 캐싱을 위한 cached_network_image
  flutter_svg: ^2.0.3   # SVG 이미지를 위한 flutter_svg
  transparent_image: ^2.0.1 # 이미지 투명도를 위한 transparent_image
  keyboard_utils_fork: ^1.0.1 # 키보드 관리를 위한 keyboard_utils_fork
  flutter_cache_manager: ^3.3.0 # 캐시 관리를 위한 flutter_cache_manager
  easy_localization: ^3.0.2 # 다국어 지원을 위한 easy_localization
  velocity_x: ^4.1.0  # UI를 위한 velocity_x
  logger: ^2.4.0  # 로그를 위한 logger
  quiver: ^3.2.1
  infinite_scroll_pagination: ^4.0.0 # 무한 스크롤을 위한 infinite_scroll_pagination
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.1 # 앱 아이콘을 위한 flutter_launcher_icons
  flutter_lints: ^5.0.0 # Lint를 위한 flutter_lints
  build_runner: ^2.4.12  # 빌드를 위한 build_runner
  riverpod_generator: ^2.4.0 # 상태 관리를 위한 riverpod_generator
  freezed: ^2.5.7 # 불변 모델 생성을 위한 freezed
  json_serializable: ^6.8.0  # JSON 파싱을 위한 json_serializable
  analyzer: ^6.7.0

flutter_launcher_icons:
  #  android: "launcher_icon"
  #  ios: "AppIcon"
  android: true
  ios: true
#  image_path_ios: "assets/icon/app_icon.png"
#  image_path_android: "assets/icon/app_icon.png"
#  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icon/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
