// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1csIIyIRxXGY5q0T9zt7QF1SS1T9Cqmk',
    appId: '1:359202154414:web:1f33a3c5385fbe25754a3f',
    messagingSenderId: '359202154414',
    projectId: 'cookfluencer',
    authDomain: 'cookfluencer.firebaseapp.com',
    storageBucket: 'cookfluencer.appspot.com',
    measurementId: 'G-YYZLQXR19Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCVLKDUclrNLBa59jIlWvt2i4NyreyMVo',
    appId: '1:359202154414:android:af25a97edd73c7ac754a3f',
    messagingSenderId: '359202154414',
    projectId: 'cookfluencer',
    storageBucket: 'cookfluencer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjsmzsyw0MqEj6Wlk3VlImt0ShJ_NvZeQ',
    appId: '1:359202154414:ios:1227c6acb1f55e75754a3f',
    messagingSenderId: '359202154414',
    projectId: 'cookfluencer',
    storageBucket: 'cookfluencer.appspot.com',
    iosBundleId: 'com.example.cookfluencer',
  );
}
