# 프로젝트의 전역 플랫폼을 정의하기 위한 주석 해제
# platform :ios, '14.0' # Xcode 설정과 맞추어 iOS 13.0 이상으로 명시
platform :ios, '14.3'

# CocoaPods 분석 통계를 비동기적으로 전송하여 Flutter 빌드 지연 시간에 영향을 줄 수 있음
ENV['COCOAPODS_DISABLE_STATS'] = 'true' # CocoaPods의 분석 통계를 비활성화하여 빌드 지연 시간 단축

# Xcode에서 사용할 프로젝트의 설정 정의
project 'Runner', {
  'Debug' => :debug, # 디버그 모드 설정
  'Profile' => :release, # 프로파일 모드 설정
  'Release' => :release, # 릴리즈 모드 설정
}

# Flutter SDK 경로를 가져오는 메서드 정의
def flutter_root
  # Flutter에서 자동 생성한 xcode 빌드 설정 파일의 경로
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)

  # 생성된 파일이 존재하는지 확인
  unless File.exist?(generated_xcode_build_settings_path) # 괄호 추가
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  # 생성된 파일을 읽고 FLUTTER_ROOT 경로 추출
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches # FLUTTER_ROOT를 찾았다면 해당 경로 반환
  end

  # FLUTTER_ROOT를 찾지 못한 경우 예외 발생
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

# Flutter 도구에서 제공하는 PodHelper를 불러오기
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Flutter iOS Podfile 설정
flutter_ios_podfile_setup

# iOS 앱 타겟 설정
target 'Runner' do
  use_frameworks! # 프레임워크를 사용하도록 설정
  use_modular_headers! # 모듈화된 헤더를 사용하도록 설정
#   pod 'AdPopcornSSP', '2.9.0'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  # 기존 pod 선언
  pod 'gRPC-C++' # gRPC C++ 라이브러리
   # Firebase 버전 고정
  pod 'Firebase/Firestore', '11.8.0' # cloud_firestore에서 요구하는 버전과 맞춤
  pod 'Firebase/Messaging', '11.8.0'
#   pod 'Google-Mobile-Ads-SDK', '11.10.0'
#   pod 'Google-Mobile-Ads-SDK', '11.9.0'

  # 모든 Flutter iOS pod 설치
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # RunnerTests 타겟 설정
  target 'RunnerTests' do
    inherit! :search_paths # 검색 경로 상속
  end
end


# 설치 후 추가 설정
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++14'
      end
    end
  end
end
