name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Flutter 설치
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # 3. 의존성 설치
      - name: Install dependencies
        run: flutter pub get

      # 4. Keystore 복원
      - name: Restore keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: echo "$KEYSTORE_FILE" | base64 --decode > android/app/cookfluencer-release-key.jks

